import type { SteamApiJson } from "../schema.ts";

/**
 * A C++ program that prints the size of every struct and the offset of every field,
 * so a test can compare the generator's layout table against a real compiler.
 * It includes no standard headers, because the Steam headers alone compile for any target.
 */
export function emitHarnessC(schema: SteamApiJson): string {
  const lines: string[] = [
    "// GENERATED by @steamworks/codegen. Prints struct layouts for comparison with layout.json.",
    '#include "steam/steam_api.h"',
    'extern "C" int printf(const char *, ...);',
    "int main() {",
  ];
  for (const s of [...schema.structs, ...schema.callback_structs]) {
    lines.push(`  printf("${s.struct} size=%u\\n", (unsigned)sizeof(${s.struct}));`);
    for (const f of s.fields) {
      lines.push(
        `  printf("  ${s.struct}.${f.fieldname} off=%u\\n", ` +
          `(unsigned)__builtin_offsetof(${s.struct}, ${f.fieldname}));`,
      );
    }
  }
  lines.push("  return 0;", "}", "");
  return lines.join("\n");
}
