import type { SteamApiJson } from "../schema.ts";

/**
 * Structs the harness cannot measure, because `steam_api.h` does not pull in a complete
 * definition. They live in headers shipped separately from the public SDK folder.
 */
const SKIP_STRUCTS = new Set([
  "SteamDatagramHostedAddress",
  "SteamDatagramGameCoordinatorServerLogin",
]);

/**
 * Fields the harness cannot take the offset of: members of anonymous unions, which the
 * JSON lists individually, and members the header declares private.
 */
/** Structs the JSON names unqualified but C++ nests inside another type. */
const C_NAMES: Record<string, string> = {
  AnalogAction_t: "SteamInputActionEvent_t::AnalogAction_t",
  DigitalAction_t: "SteamInputActionEvent_t::DigitalAction_t",
};

const SKIP_FIELDS = new Set([
  "SteamNetworkingConfigValue_t.m_int32",
  "SteamNetworkingConfigValue_t.m_int64",
  "SteamNetworkingConfigValue_t.m_float",
  "SteamNetworkingConfigValue_t.m_string",
  "SteamNetworkingConfigValue_t.m_functionPtr",
]);

/**
 * A C++ program that prints the size of every struct and the offset of every field, so a
 * test can compare the generator's layout table against a real compiler. It includes no
 * standard headers, because the Steam headers alone compile for any target.
 */
export function emitHarnessC(schema: SteamApiJson): string {
  const lines: string[] = [
    "// GENERATED by @steamworks/codegen. Prints struct layouts for comparison with layout.json.",
    '#include "steam/steam_api.h"',
    // Game server callbacks live here; steam_api.h does not pull them in.
    '#include "steam/steam_gameserver.h"',
    // Only forward declared by the headers above.
    '#include "steam/steamnetworkingfakeip.h"',
    'extern "C" int printf(const char *, ...);',
    "int main() {",
  ];
  for (const s of [...schema.structs, ...schema.callback_structs]) {
    if (SKIP_STRUCTS.has(s.struct)) continue;
    const cName = C_NAMES[s.struct] ?? s.struct;
    lines.push(`  printf("${s.struct} size=%u\\n", (unsigned)sizeof(${cName}));`);
    for (const f of s.fields) {
      if (f.private) continue;
      if (SKIP_FIELDS.has(`${s.struct}.${f.fieldname}`)) continue;
      lines.push(
        `  printf("  ${s.struct}.${f.fieldname} off=%u\\n", ` +
          `(unsigned)__builtin_offsetof(${cName}, ${f.fieldname}));`,
      );
    }
  }
  lines.push("  return 0;", "}", "");
  return lines.join("\n");
}
