/** Banner placed at the top of every generated file. */
export function header(sdkVersion: string): string {
  return `// GENERATED by @steamworks/codegen from steam_api.json (SDK ${sdkVersion}). Do not edit.\n\n`;
}
